version: '3'

services:
        db:
                image: mysql:5.7
                ports:
                        - "3306:3306"
                environment:
                        MYSQL_DATABASE: 'test_db'
                        MYSQL_USER: 'root'
                        MYSQL_PASSWORD: 'password'
                        MYSQL_ROOT_PASSWORD: 'password'
                volumes:
                        - test_volume:/var/lib/mysql

                          
        drf:
                build: .
                command: python manage.py runserver 0.0.0.0:8000
                ports:
                        - "8000:8000"
                volumes:
                        - .:/app

volumes:
        test_volume:
