# Generated by Django 3.0.8 on 2020-07-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.CharField(default='rhdiddl', max_length=100),
            preserve_default=False,
        ),
    ]
