# Generated by Django 3.0.8 on 2020-07-12 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_public',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
